spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres2
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      initialization-mode: always
      continue-on-error: false
  jpa:
    open-in-view: false
    show-sql: true
    format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      ddl-auto: create
logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n'
  level:
    root: INFO
    web: DEBUG
    com.msieiro.DevNewsWebScrapper: DEBUG
